INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('1', '0', '卖剩鸭视频网站', null, '1', null,'&#xe68e;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('2', '1', '基础管理', null, '0', null, '&#xe653;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('3', '1', '业务管理', null, '0', null, '&#xe663;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('4', '1', '系统管理', null, '1', null, '&#xe716;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('5', '1', '统计分析', null, '0', null, '&#xe629;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('6', '2', '用户管理', '/bussiness/toUserManager.html', '0', null, '&#xe770;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('18', '3', '日志管理', '/bussiness/toLogManager.html', '0', null,  '&#xe655;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('19', '4', '菜单管理', '/system//toMenuManager.html', '0', null,  '&#xe60f;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('20', '4', '角色管理', '/system/toRoleManager.html', '0', null,  '&#xe612;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('21', '4', '管理员管理', '/system/toAdministratorManager.html', '0', null, '&#xe770;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('22', '4', '日志管理', '/system/toAdministratorLogManager.html', '0', null,  '&#xe655;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('23', '4', '公告管理', '/system/toNewsManager.html', '0', null,  '&#xe645;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('24', '4', '数据源监控', '/druid/index.html', '0', null,  '&#xe857;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('25', '5', '系统访问统计', '/admin/stat/toOnlineStat.html', '0', null,  '&#xe62c;', '1',NOW(),NOW());
INSERT INTO `sys_menu` (id,pid,title,href,spread,target,icon,available,update_time,create_time) VALUES ('26', '4', '权限管理', '/system/toPermissionManager.html', '0', null,  '&#xe672;', '1',NOW(),NOW());
